"""empty message

Revision ID: be7bf8bb8a33
Revises: 19f31f11623a
Create Date: 2025-02-22 12:07:04.888917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7bf8bb8a33'
down_revision = '19f31f11623a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
